Немнонов Артём 3-2П9
Kostroma-Polytechnic-College/paper-io__3-2P9 pull request #2
Opened 2021-11-19 06:28 UTC by DemonEyes12

Реализовано меню

2021-11-24 05:55 UTC, YuriSilenok requested changes
Устранить [эти](https://www.codefactor.io/repository/github/kostroma-polytechnic-college/paper-io__3-2p9/pull/2 )проблемы

2021-11-24 05:55 UTC, YuriSilenok commented on paper-io/Game.cs
> +        }
Требуется комментарии к коду

2021-11-24 05:55 UTC, YuriSilenok commented on paper-io/Player.cs
> +    public class Player
требуется комментарий к коду

2021-11-24 05:56 UTC, YuriSilenok commented on paper-io/Room.xaml.cs
> +        private void MovePlayer(object sender, EventArgs e)
комментарий к методу

2021-11-24 05:56 UTC, YuriSilenok commented on paper-io/Start.xaml.cs
> +        private void Button_Click(object sender, RoutedEventArgs e)
комментарий к методу

2021-11-24 06:29 UTC, YuriSilenok requested changes
Нужно больше комментариев
![image](https://user-images.githubusercontent.com/14871471/143186412-69bc7e1c-7475-4ca5-9af8-52e6c22f9554.png)

2021-11-24 06:29 UTC, YuriSilenok commented on paper-io/Game.cs
> +    class Game
Ожидаю комментарии от автора

2021-11-24 06:29 UTC, YuriSilenok commented on paper-io/Game.cs
> +        public Player[] Players;
Ожидаю комментарии от автора

2021-11-24 06:29 UTC, YuriSilenok commented on paper-io/Game.cs
> +        public Player[,] Room;
Ожидаю комментарии от автора

2021-11-24 06:29 UTC, YuriSilenok commented on paper-io/Game.cs
> +        public Game(byte n)
Ожидаю комментарии от автора

2021-11-24 06:29 UTC, YuriSilenok commented on paper-io/Room.xaml.cs
> +        enum Direction { left, right, up, down}
Ожидаю комментарии от автора

2021-11-24 06:29 UTC, YuriSilenok commented on paper-io/Room.xaml.cs
> +        double x = 0;
Ожидаю комментарии от автора

2021-11-24 06:29 UTC, YuriSilenok commented on paper-io/Room.xaml.cs
> +        double y = 0;
Ожидаю комментарии от автора

2021-11-24 06:29 UTC, YuriSilenok commented on paper-io/Room.xaml.cs
> +        private void MovePlayer(object sender, EventArgs e)
Ожидаю комментарии от автора

2021-11-24 06:29 UTC, YuriSilenok commented on paper-io/Start.xaml.cs
> +        Game game;
Ожидаю комментарии от автора

2021-11-24 06:29 UTC, YuriSilenok commented on paper-io/Start.xaml.cs
> +        Room room;
Ожидаю комментарии от автора

2021-11-24 06:29 UTC, YuriSilenok commented on paper-io/Start.xaml.cs
> +        private void Button_Click(object sender, RoutedEventArgs e)
Ожидаю комментарии от автора

2021-11-24 17:36 UTC, YuriSilenok requested changes
А вас не смущает что у вас репозиторий в репозитории?
paper-io__2-1P11

2021-11-24 17:36 UTC, YuriSilenok commented on paper-io/Game.cs
> +    ///
шаблон комментария вижу, а где шам коммент?

2021-11-24 17:36 UTC, YuriSilenok commented on paper-io/Game.cs
> +        ///
Где коммент?

2021-11-24 17:36 UTC, YuriSilenok commented on paper-io/Game.cs
> +        ///
Где коммент?

2021-11-24 17:36 UTC, YuriSilenok commented on paper-io/Game.cs
> +        /// <param name="n"></param>
Где коммент?

2021-11-24 17:36 UTC, YuriSilenok commented on paper-io/Player.cs
> +    ///
Где коммент?

2021-11-24 17:36 UTC, YuriSilenok commented on paper-io/Room.xaml.cs
> +        /// свойство для задачи нажатий клавиш через которые игрок решает куда ему двигатся
Мне кажется это свойство игрока, у игрока нужно определять перечисление, в форме мы только обрабатываем нажатия клавишь и задаем направление движения игроку. И это не свойство, а перечисление.

2021-11-24 17:36 UTC, YuriSilenok commented on paper-io/Room.xaml.cs
> +        double x = 0;
не вижу смысла в храненении здесь x и y

2021-11-24 17:36 UTC, YuriSilenok commented on paper-io/Room.xaml.cs
> +        #endregion
накодили, уберите за собой

2021-11-24 17:36 UTC, YuriSilenok commented on paper-io/Start.xaml.cs
> +        Room room;
Зачем это в поле класса формы?

2021-11-24 17:36 UTC, YuriSilenok commented on paper-io/Start.xaml.cs
> +        /// <param name="e"></param>
Где описание аргументов?

2021-11-24 17:36 UTC, YuriSilenok commented on paper-io/Start.xaml.cs
> +                    game = new Game(n);
Каким образом передается game в форму Room?

2021-11-25 08:12 UTC, JollyFoxy commented on paper-io/Game.cs
> +        }
В методе создаётся игровое поле размером N*N, где N = количество игроков * 10

2021-11-25 08:15 UTC, JollyFoxy commented on paper-io/Player.cs
> +    public class Player
Заглушка класса Player

2021-11-25 11:09 UTC, YuriSilenok commented
Если что, то еще не все исправлено

2021-11-27 05:33 UTC, YuriSilenok requested changes

2021-11-27 05:33 UTC, YuriSilenok commented on paper-io/Game.cs
> +        /// Размерность поля
Это не размерность поля

2021-11-27 05:33 UTC, YuriSilenok commented on paper-io/Game.cs
> +        /// <param name="n"></param> Количество игроков
описание входного параметра?

2021-11-27 05:33 UTC, YuriSilenok commented on paper-io/Player.cs
> +    /// Заглушка класса Player
Зачем нужен этот класс

2021-11-27 05:33 UTC, YuriSilenok commented on paper-io/Start.xaml.cs
> +         Game game;
Что с отступом?

2021-11-27 06:48 UTC, YuriSilenok approved these changes

2021-11-27 06:48 UTC, merged